// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45t8-CxB2YmadpKQVm1IWExKPUwD2rRE',
    appId: '1:230644165555:web:af7f6aab8da21fac7d39c6',
    messagingSenderId: '230644165555',
    projectId: 'final-evnav',
    authDomain: 'final-evnav.firebaseapp.com',
    databaseURL: 'https://final-evnav-default-rtdb.firebaseio.com',
    storageBucket: 'final-evnav.appspot.com',
    measurementId: 'G-M15WPK5NMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeGtD-y0OsyKshcFkz5km24kNEU-CszY',
    appId: '1:230644165555:android:49024a184769f1b37d39c6',
    messagingSenderId: '230644165555',
    projectId: 'final-evnav',
    databaseURL: 'https://final-evnav-default-rtdb.firebaseio.com',
    storageBucket: 'final-evnav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2TzQ8THSMwceKVwtbG62wwsGJ_S7uc0',
    appId: '1:230644165555:ios:49b07a773aba7bca7d39c6',
    messagingSenderId: '230644165555',
    projectId: 'final-evnav',
    databaseURL: 'https://final-evnav-default-rtdb.firebaseio.com',
    storageBucket: 'final-evnav.appspot.com',
    iosClientId: '230644165555-ovnbci6v1rfcagefrnidnea1egk4m824.apps.googleusercontent.com',
    iosBundleId: 'com.example.evnav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2TzQ8THSMwceKVwtbG62wwsGJ_S7uc0',
    appId: '1:230644165555:ios:49b07a773aba7bca7d39c6',
    messagingSenderId: '230644165555',
    projectId: 'final-evnav',
    databaseURL: 'https://final-evnav-default-rtdb.firebaseio.com',
    storageBucket: 'final-evnav.appspot.com',
    iosClientId: '230644165555-ovnbci6v1rfcagefrnidnea1egk4m824.apps.googleusercontent.com',
    iosBundleId: 'com.example.evnav',
  );
}
